<?php

use Illuminate\Database\Seeder;
use IPMEDT5\Beer;

class BeersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Alle bieren van https://nl.wikipedia.org/wiki/Lijst_van_Nederlandse_bieren
        $beers = [
            ["name" => "Bavaria 8.6 Gold", "percentage" => 0.000],
            ["name" => "Emelisse TIPA", "percentage" => 0.000],
            ["name" => "Maximus Lente", "percentage" => 0.000],
            ["name" => "Sir Turnaround", "percentage" => 0.000],
            ["name" => "Amstel 0.0", "percentage" => 0.000],
            ["name" => "Amstel Radler 0.0%", "percentage" => 0.000],
            ["name" => "Bavaria 0.0%", "percentage" => 0.000],
            ["name" => "Bavaria 0.0% Gold", "percentage" => 0.000],
            ["name" => "Bavaria 0.0% Wit", "percentage" => 0.000],
            ["name" => "Bavaria 0.0% Rosé", "percentage" => 0.000],
            ["name" => "Bavaria 0.0% Apple", "percentage" => 0.000],
            ["name" => "Bavaria 0.0% Lemon", "percentage" => 0.000],
            ["name" => "Bavaria 0.0% Peach", "percentage" => 0.000],
            ["name" => "Budels Malt", "percentage" => 0.000],
            ["name" => "Wieckse Radler 0.0%", "percentage" => 0.000],
            ["name" => "Wieckse Rosé 0.0%", "percentage" => 0.000],
            ["name" => "Wieckse Witte 0.0%", "percentage" => 0.000],
            ["name" => "Grolsch Stender Alcoholarm", "percentage" => 0.005],
            ["name" => "Grolsch Stender Lemon & Lime", "percentage" => 0.005],
            ["name" => "Grolsch Stender Red Orange", "percentage" => 0.005],
            ["name" => "Amstel Radler", "percentage" => 0.020],
            ["name" => "Amstel Radler Grapefruit", "percentage" => 0.020],
            ["name" => "Bavaria Radler", "percentage" => 0.020],
            ["name" => "Dommelsch Oud Bruin", "percentage" => 0.020],
            ["name" => "Grolsch Radler", "percentage" => 0.020],
            ["name" => "Alfa Oud Bruin", "percentage" => 0.025],
            ["name" => "Gulpener Oud Bruin", "percentage" => 0.025],
            ["name" => "Heineken Oud Bruin", "percentage" => 0.025],
            ["name" => "Bavaria Oud Bruin", "percentage" => 0.030],
            ["name" => "Amstel Light", "percentage" => 0.035],
            ["name" => "Brand Oud Bruin", "percentage" => 0.035],
            ["name" => "Budels Oud Bruin", "percentage" => 0.035],
            ["name" => "Gulpener Korenwolf Rosé", "percentage" => 0.035],
            ["name" => "Java Kriek", "percentage" => 0.035],
            ["name" => "Lindeboom Oud Bruin", "percentage" => 0.035],
            ["name" => "Mestreechs Aajt", "percentage" => 0.035],
            ["name" => "Amstel Blond", "percentage" => 0.040],
            ["name" => "Jopen Adriaan Rosé", "percentage" => 0.040],
            ["name" => "Geboren & Getogen", "percentage" => 0.040],
            ["name" => "Miss Hooter", "percentage" => 0.040],
            ["name" => "De Klok Blond", "percentage" => 0.042],
            ["name" => "Bed & Breakfast", "percentage" => 0.044],
            ["name" => "Berghoeve Khoppig", "percentage" => 0.045],
            ["name" => "Budels Honing Bio", "percentage" => 0.045],
            ["name" => "Croy 1671", "percentage" => 0.045],
            ["name" => "Croyse Witte", "percentage" => 0.045],
            ["name" => "Croyse Bock", "percentage" => 0.045],
            ["name" => "Gulpener Sjoes", "percentage" => 0.045],
            ["name" => "Jopen Gerstebier", "percentage" => 0.045],
            ["name" => "Amerikaans", "percentage" => 0.045],
            ["name" => "Engels", "percentage" => 0.045],
            ["name" => "Op & Top", "percentage" => 0.045],
            ["name" => "X-Porter", "percentage" => 0.045],
            ["name" => "Xtreem Warrior", "percentage" => 0.046],
            ["name" => "La Trappe Puur", "percentage" => 0.047],
            ["name" => "Amersfoorts Blond", "percentage" => 0.048],
            ["name" => "Brouwers Pilsener", "percentage" => 0.048],
            ["name" => "Hollandia", "percentage" => 0.048],
            ["name" => "Schansbier Tarwe", "percentage" => 0.048],
            ["name" => "De Prael Milkstout", "percentage" => 0.049],
            ["name" => "Steinder Wit", "percentage" => 0.049],
            ["name" => "Mr. Feathers", "percentage" => 0.049],
            ["name" => "Alfa Edel Pils", "percentage" => 0.050],
            ["name" => "Amstel Pilsener", "percentage" => 0.050],
            ["name" => "Amstel 1870", "percentage" => 0.050],
            ["name" => "Arm+Zalig", "percentage" => 0.050],
            ["name" => "Batavier", "percentage" => 0.050],
            ["name" => "Bavaria Premium Pilsener", "percentage" => 0.050],
            ["name" => "Bavaria Premium Lager", "percentage" => 0.050],
            ["name" => "Bavaria Gluten free Premium Pilsener", "percentage" => 0.050],
            ["name" => "Brand Pilsener", "percentage" => 0.050],
            ["name" => "Bronckhorster Eigenweiss", "percentage" => 0.050],
            ["name" => "Budels Pils", "percentage" => 0.050],
            ["name" => "Budels Pilsener Bio", "percentage" => 0.050],
            ["name" => "Budels Capucijn", "percentage" => 0.050],
            ["name" => "Dommelsch Pilsener", "percentage" => 0.050],
            ["name" => "Emelisse Urtype Pilsener", "percentage" => 0.050],
            ["name" => "Emelisse Witbier", "percentage" => 0.050],
            ["name" => "Grolsch Premium Pilsner", "percentage" => 0.050],
            ["name" => "Gulpener Pilsner", "percentage" => 0.050],
            ["name" => "Gulpener Biologisch Ur-Pilsner", "percentage" => 0.050],
            ["name" => "Gulpener Korenwolf", "percentage" => 0.050],
            ["name" => "Grunn Goudhaantje", "percentage" => 0.050],
            ["name" => "Heineken", "percentage" => 0.050],
            ["name" => "Hengelo Bier", "percentage" => 0.050],
            ["name" => "Hertog Jan Weizener", "percentage" => 0.050],
            ["name" => "Hoeksch Wit", "percentage" => 0.050],
            ["name" => "Jaeger", "percentage" => 0.050],
            ["name" => "Java Premium", "percentage" => 0.050],
            ["name" => "Jopen Adriaan", "percentage" => 0.050],
            ["name" => "Jopen Malle Babbe", "percentage" => 0.050],
            ["name" => "Keizerskroon", "percentage" => 0.050],
            ["name" => "De Leckere Pilsener", "percentage" => 0.050],
            ["name" => "De Leckere Willibrord", "percentage" => 0.050],
            ["name" => "De Leckere Witte Vrouwen", "percentage" => 0.050],
            ["name" => "Lindeboom Pilsener", "percentage" => 0.050],
            ["name" => "Maastrichts Blont", "percentage" => 0.050],
            ["name" => "Moreeke", "percentage" => 0.050],
            ["name" => "Paladijn", "percentage" => 0.050],
            ["name" => "India Pale Ale", "percentage" => 0.050],
            ["name" => "Stoombier", "percentage" => 0.050],
            ["name" => "Pitt Bier", "percentage" => 0.050],
            ["name" => "Plzeň", "percentage" => 0.050],
            ["name" => "Ruw+Bolster", "percentage" => 0.050],
            ["name" => "Sancti Adalberti Egmondse Witte", "percentage" => 0.050],
            ["name" => "Schansbier Pils", "percentage" => 0.050],
            ["name" => "Schansbier Schwarz", "percentage" => 0.050],
            ["name" => "Scherp+Zinnig", "percentage" => 0.050],
            ["name" => "Stoombier", "percentage" => 0.050],
            ["name" => "Texels Wit", "percentage" => 0.050],
            ["name" => "Twents Premium Pils", "percentage" => 0.050],
            ["name" => "Twents Wit", "percentage" => 0.050],
            ["name" => "Twents Rosé", "percentage" => 0.050],
            ["name" => "Us Heit Twels Pilsener", "percentage" => 0.050],
            ["name" => "Us Heit Twels Speciaal", "percentage" => 0.050],
            ["name" => "Venloosch Alt", "percentage" => 0.050],
            ["name" => "Venloosch Wit", "percentage" => 0.050],
            ["name" => "Wieckse Rosé", "percentage" => 0.050],
            ["name" => "Wieckse Witte", "percentage" => 0.050],
            ["name" => "Wispe Wit", "percentage" => 0.050],
            ["name" => "Zeeuwsche Witte", "percentage" => 0.050],
            ["name" => "Brand Weizen", "percentage" => 0.051],
            ["name" => "De Veldwachter", "percentage" => 0.051],
            ["name" => "Euleteul Zomer", "percentage" => 0.051],
            ["name" => "Hertog Jan Pilsener", "percentage" => 0.051],
            ["name" => "Hamer & Sikkel", "percentage" => 0.051],
            ["name" => "Alfa Puur Ongefilterd", "percentage" => 0.052],
            ["name" => "De Leckere Gulden Craen", "percentage" => 0.052],
            ["name" => "Oersoep Kort Amerikaans II", "percentage" => 0.052],
            ["name" => "Weizen", "percentage" => 0.052],
            ["name" => "Gulpener Biologisch Ur-Amber", "percentage" => 0.053],
            ["name" => "Gulpener Biologisch Ur-Weizen", "percentage" => 0.053],
            ["name" => "Jopen Jacobus RPA", "percentage" => 0.053],
            ["name" => "Praght Pionier", "percentage" => 0.053],
            ["name" => "Vulcaan", "percentage" => 0.053],
            ["name" => "De Prael Weizen", "percentage" => 0.054],
            ["name" => "1410", "percentage" => 0.055],
            ["name" => "Antje van Gerrebrandje", "percentage" => 0.055],
            ["name" => "Brand UP", "percentage" => 0.055],
            ["name" => "Burg Bier Veluws Blond", "percentage" => 0.055],
            ["name" => "Burg Bier Witte Pauw", "percentage" => 0.055],
            ["name" => "Butenbiëntke", "percentage" => 0.055],
            ["name" => "Croyale", "percentage" => 0.055],
            ["name" => "Croy Stout", "percentage" => 0.055],
            ["name" => "Gouverneur speciale 140", "percentage" => 0.055],
            ["name" => "Grolsch Puur Weizen", "percentage" => 0.055],
            ["name" => "Gulpener Château Neubourg Pilsner", "percentage" => 0.055],
            ["name" => "Grunn Rode Hoan", "percentage" => 0.055],
            ["name" => "Helderse Jongens Dorus", "percentage" => 0.055],
            ["name" => "Hillegonda Blank", "percentage" => 0.055],
            ["name" => "Hillegonda Rooie Kers", "percentage" => 0.055],
            ["name" => "Jopen Extra Stout", "percentage" => 0.055],
            ["name" => "Witte Trappist", "percentage" => 0.055],
            ["name" => "Oersoep La Petite Rouge", "percentage" => 0.055],
            ["name" => "Swinckels' Volmaakt", "percentage" => 0.055],
            ["name" => "Texels Eyerlander", "percentage" => 0.055],
            ["name" => "Twents Oer Pils", "percentage" => 0.055],
            ["name" => "Breugems Amber", "percentage" => 0.056],
            ["name" => "Vlaams & Hollands", "percentage" => 0.056],
            ["name" => "Otter S.B.", "percentage" => 0.056],
            ["name" => "Zomers Witje", "percentage" => 0.056],
            ["name" => "Berghoeve Helders Goud", "percentage" => 0.057],
            ["name" => "Oersoep Holy Smoke", "percentage" => 0.057],
            ["name" => "De Prael Bitterblond", "percentage" => 0.057],
            ["name" => "De Prael I.P.A.", "percentage" => 0.057],
            ["name" => "Barnstien Amelander Amberbier", "percentage" => 0.058],
            ["name" => "Zonnelief", "percentage" => 0.058],
            ["name" => "Schansbier 6", "percentage" => 0.058],
            ["name" => "Bird of Prey IPA", "percentage" => 0.058],
            ["name" => "Us Heit Frysk Bier", "percentage" => 0.058],
            ["name" => "De Blondine", "percentage" => 0.059],
            ["name" => "Limburgs Blond", "percentage" => 0.059],
            ["name" => "Appelbier", "percentage" => 0.060],
            ["name" => "Blonde Ros", "percentage" => 0.060],
            ["name" => "Breugems Dubbel", "percentage" => 0.060],
            ["name" => "Bronckhorster Royal Rha", "percentage" => 0.060],
            ["name" => "Budels Goudblond", "percentage" => 0.060],
            ["name" => "Burg Bier Springbok", "percentage" => 0.060],
            ["name" => "Christoffel Bier", "percentage" => 0.060],
            ["name" => "Christoffel Wijs", "percentage" => 0.060],
            ["name" => "Dampegheest Zomerskarrel", "percentage" => 0.060],
            ["name" => "Dichte Mist", "percentage" => 0.060],
            ["name" => "Dikke Deur", "percentage" => 0.060],
            ["name" => "Gerardus Wittems Kloosterbier Blond", "percentage" => 0.060],
            ["name" => "Gulpener Biologisch Ur-Hop", "percentage" => 0.060],
            ["name" => "Grunn Hail en Zegen", "percentage" => 0.060],
            ["name" => "Hersevoort (bier)", "percentage" => 0.060],
            ["name" => "'t Leste Lot", "percentage" => 0.060],
            ["name" => "Maximus Brutus", "percentage" => 0.060],
            ["name" => "Maximus Pandora", "percentage" => 0.060],
            ["name" => "Nero", "percentage" => 0.060],
            ["name" => "Oirschots (Bier)", "percentage" => 0.060],
            ["name" => "Bock", "percentage" => 0.060],
            ["name" => "Saison", "percentage" => 0.060],
            ["name" => "Ramses Poolvos", "percentage" => 0.060],
            ["name" => "Rosso", "percentage" => 0.060],
            ["name" => "Schansbier Blond", "percentage" => 0.060],
            ["name" => "Texels Skuumkoppe", "percentage" => 0.060],
            ["name" => "Texels Goudkoppe", "percentage" => 0.060],
            ["name" => "Twents Amber", "percentage" => 0.060],
            ["name" => "Us Heit Buorren Bier", "percentage" => 0.060],
            ["name" => "Us Heit Twels Bokbier", "percentage" => 0.060],
            ["name" => "Wispe Blond", "percentage" => 0.060],
            ["name" => "De Brunette", "percentage" => 0.061],
            ["name" => "Leidsch Morsporter", "percentage" => 0.061],
            ["name" => "De Prael Pale Ale", "percentage" => 0.061],
            ["name" => "Botterik", "percentage" => 0.062],
            ["name" => "Breugems Lente Zoentje", "percentage" => 0.062],
            ["name" => "Eem Blond", "percentage" => 0.062],
            ["name" => "Emelisse Rauchbier", "percentage" => 0.062],
            ["name" => "Hertog Jan Oerblond", "percentage" => 0.062],
            ["name" => "Hoeksch 1300", "percentage" => 0.062],
            ["name" => "Hoeksch Eiken", "percentage" => 0.062],
            ["name" => "De Molen Bock", "percentage" => 0.062],
            ["name" => "Vuur & Vlam", "percentage" => 0.062],
            ["name" => "Ramses Moby Dick", "percentage" => 0.062],
            ["name" => "Tasty Lady", "percentage" => 0.062],
            ["name" => "Veluws Heidebierde", "percentage" => 0.062],
            ["name" => "Witte Klavervier Blond Hoppenbier", "percentage" => 0.062],
            ["name" => "Breugems Blond", "percentage" => 0.063],
            ["name" => "Rolduc Abdij Bier", "percentage" => 0.063],
            ["name" => "Skutehôn", "percentage" => 0.063],
            ["name" => "SNAB Pale Ale", "percentage" => 0.063],
            ["name" => "Leidsch Aaipiejee", "percentage" => 0.064],
            ["name" => "Limburgs Dubbel", "percentage" => 0.064],
            ["name" => "De Prael Dortmunder", "percentage" => 0.064],
            ["name" => "Texels Dubbel", "percentage" => 0.064],
            ["name" => "Texels Skimme", "percentage" => 0.064],
            ["name" => "Alfa Bokbier", "percentage" => 0.065],
            ["name" => "Alfa Lente Bok", "percentage" => 0.065],
            ["name" => "Apeldoorns Stadsbier", "percentage" => 0.065],
            ["name" => "Bavaria Hooghe Bock", "percentage" => 0.065],
            ["name" => "Bavaria Spring Bock", "percentage" => 0.065],
            ["name" => "Bavaria Tarwe Bock", "percentage" => 0.065],
            ["name" => "Bij 't Roaie Hek", "percentage" => 0.065],
            ["name" => "Bikkelha'd", "percentage" => 0.065],
            ["name" => "Herfstbok", "percentage" => 0.065],
            ["name" => "Lentebok", "percentage" => 0.065],
            ["name" => "Brand Imperator", "percentage" => 0.065],
            ["name" => "Brand Lentebock", "percentage" => 0.065],
            ["name" => "Bronckhorster Blond", "percentage" => 0.065],
            ["name" => "Budels Herfstbock", "percentage" => 0.065],
            ["name" => "Budels Lentebock", "percentage" => 0.065],
            ["name" => "Dobbele Java", "percentage" => 0.065],
            ["name" => "Double Saison", "percentage" => 0.065],
            ["name" => "Dubbel+Dik", "percentage" => 0.065],
            ["name" => "Duits & Lauret Blond", "percentage" => 0.065],
            ["name" => "Duits & Lauret Stout", "percentage" => 0.065],
            ["name" => "Gouverneur Blonde", "percentage" => 0.065],
            ["name" => "Gouverneur Brune", "percentage" => 0.065],
            ["name" => "Grolsch Frisse Lentebok", "percentage" => 0.065],
            ["name" => "Grolsch Rijke Herfstbok", "percentage" => 0.065],
            ["name" => "Gulpener LenteBock", "percentage" => 0.065],
            ["name" => "Gulpener HerfstBock", "percentage" => 0.065],
            ["name" => "Halbe", "percentage" => 0.065],
            ["name" => "Heineken Tarwebok", "percentage" => 0.065],
            ["name" => "Herfstbock", "percentage" => 0.065],
            ["name" => "Hertog Jan Bockbier", "percentage" => 0.065],
            ["name" => "Hop met de Gijt", "percentage" => 0.065],
            ["name" => "Hop met de Gijt Speciale Editie", "percentage" => 0.065],
            ["name" => "IJbok", "percentage" => 0.065],
            ["name" => "Jopen 4-Granen Bok", "percentage" => 0.065],
            ["name" => "La Trappe Blond", "percentage" => 0.065],
            ["name" => "La Trappe Dubbel", "percentage" => 0.065],
            ["name" => "Lazarus", "percentage" => 0.065],
            ["name" => "De Leckere Crom Hout", "percentage" => 0.065],
            ["name" => "De Leckere Rode Toren", "percentage" => 0.065],
            ["name" => "Leidsch Blond", "percentage" => 0.065],
            ["name" => "Lindeboom Herfstbock", "percentage" => 0.065],
            ["name" => "Meibock", "percentage" => 0.065],
            ["name" => "Natte", "percentage" => 0.065],
            ["name" => "Oersoep De Wilde Weg", "percentage" => 0.065],
            ["name" => "Lammetjes", "percentage" => 0.065],
            ["name" => "Ramses Hop", "percentage" => 0.065],
            ["name" => "Roock", "percentage" => 0.065],
            ["name" => "Schansbier Herfstbok", "percentage" => 0.065],
            ["name" => "Schansbier Voorjaarsbier", "percentage" => 0.065],
            ["name" => "Scheepsrecht", "percentage" => 0.065],
            ["name" => "Twents Bok", "percentage" => 0.065],
            ["name" => "Veluwse Schavuyt", "percentage" => 0.065],
            ["name" => "Zonnestraal", "percentage" => 0.065],
            ["name" => "Ramses den dorstige Tijger", "percentage" => 0.067],
            ["name" => "Xtreem Centennial", "percentage" => 0.067],
            ["name" => "Brutaal Blondje", "percentage" => 0.068],
            ["name" => "Eem Bitter", "percentage" => 0.068],
            ["name" => "Emelisse Blond", "percentage" => 0.068],
            ["name" => "Jopen Hoppenbier", "percentage" => 0.068],
            ["name" => "DBier", "percentage" => 0.069],
            ["name" => "Amstel Bock", "percentage" => 0.070],
            ["name" => "Amstel Gold", "percentage" => 0.070],
            ["name" => "Belle & Forte", "percentage" => 0.070],
            ["name" => "Berghoeve Hammer Schout", "percentage" => 0.070],
            ["name" => "Brand IPA", "percentage" => 0.070],
            ["name" => "Burg Bier Veluws Bruun", "percentage" => 0.070],
            ["name" => "Eem Donker", "percentage" => 0.070],
            ["name" => "Eem Bok", "percentage" => 0.070],
            ["name" => "Emelisse Dubbel", "percentage" => 0.070],
            ["name" => "Gerardus Wittems Kloosterbier Dubbel", "percentage" => 0.070],
            ["name" => "Gijtebok", "percentage" => 0.070],
            ["name" => "Gulpener Dort", "percentage" => 0.070],
            ["name" => "Heilooër Blond", "percentage" => 0.070],
            ["name" => "Helderse Jongens Napoleon", "percentage" => 0.070],
            ["name" => "Hertog Jan Dubbel", "percentage" => 0.070],
            ["name" => "Hertog Jan Lentebock", "percentage" => 0.070],
            ["name" => "IJwit", "percentage" => 0.070],
            ["name" => "Jopen Lentebier", "percentage" => 0.070],
            ["name" => "Jopen Witte Rook", "percentage" => 0.070],
            ["name" => "Loodsbier", "percentage" => 0.070],
            ["name" => "Oude Schaterhand I.P.A.", "percentage" => 0.070],
            ["name" => "Paasij", "percentage" => 0.070],
            ["name" => "DIPA", "percentage" => 0.070],
            ["name" => "Pracht Roockbock", "percentage" => 0.070],
            ["name" => "Saens Bokkie", "percentage" => 0.070],
            ["name" => "Schansbier Saison", "percentage" => 0.070],
            ["name" => "Stout+Moedig", "percentage" => 0.070],
            ["name" => "Texels Bockbier", "percentage" => 0.070],
            ["name" => "Twents Honing Tripel", "percentage" => 0.070],
            ["name" => "Ut 1e Kieftai", "percentage" => 0.070],
            ["name" => "Van Vollenhoven Extra Stout", "percentage" => 0.070],
            ["name" => "Venloos Paeterke Döbbel", "percentage" => 0.070],
            ["name" => "Wispe Bock", "percentage" => 0.070],
            ["name" => "Witte Klavervier Poorter", "percentage" => 0.070],
            ["name" => "Zuidwester", "percentage" => 0.070],
            ["name" => "Rooie Dop Chica Americana IPA", "percentage" => 0.071],
            ["name" => "De Manke Monnik", "percentage" => 0.072],
            ["name" => "Emelisse Herfstbock", "percentage" => 0.072],
            ["name" => "De Leckere Pontificale", "percentage" => 0.072],
            ["name" => "La Trappe Bockbier", "percentage" => 0.073],
            ["name" => "Xtreem Chinook", "percentage" => 0.073],
            ["name" => "Alfa Super Dortmunder", "percentage" => 0.075],
            ["name" => "Amstel Sterk", "percentage" => 0.075],
            ["name" => "Avondrood", "percentage" => 0.075],
            ["name" => "Beerze", "percentage" => 0.075],
            ["name" => "Brand Dubbelbock", "percentage" => 0.075],
            ["name" => "Brand Sylvester", "percentage" => 0.075],
            ["name" => "Budels Kolos", "percentage" => 0.075],
            ["name" => "Cherubijn", "percentage" => 0.075],
            ["name" => "Croy Blond", "percentage" => 0.075],
            ["name" => "Croy Dubbel", "percentage" => 0.075],
            ["name" => "Dampegheest Bockbier", "percentage" => 0.075],
            ["name" => "Dampegheest Rookbock", "percentage" => 0.075],
            ["name" => "Donder", "percentage" => 0.075],
            ["name" => "Duits & Lauret Dubbelbock", "percentage" => 0.075],
            ["name" => "Duits & Lauret TeVreden", "percentage" => 0.075],
            ["name" => "Emelisse Lentebock", "percentage" => 0.075],
            ["name" => "Ezelenbok", "percentage" => 0.075],
            ["name" => "Gouverneur Dubbelbock", "percentage" => 0.075],
            ["name" => "Gouverneur Stout", "percentage" => 0.075],
            ["name" => "Grunn Bock", "percentage" => 0.075],
            ["name" => "Hertog Jan Karakter", "percentage" => 0.075],
            ["name" => "Hopla", "percentage" => 0.075],
            ["name" => "Koning Honing", "percentage" => 0.075],
            ["name" => "La Trappe Isid'or", "percentage" => 0.075],
            ["name" => "De Leckere Paulus", "percentage" => 0.075],
            ["name" => "Jaar & Dag", "percentage" => 0.075],
            ["name" => "De Prael Tripel", "percentage" => 0.075],
            ["name" => "Sancti Adalberti Egmondse Tripel", "percentage" => 0.075],
            ["name" => "Texels Winterbier", "percentage" => 0.075],
            ["name" => "Us Heit Elfstedenbier", "percentage" => 0.075],
            ["name" => "Us Heit Kerstbier", "percentage" => 0.075],
            ["name" => "Xtreem Winter", "percentage" => 0.075],
            ["name" => "Dubbellam", "percentage" => 0.076],
            ["name" => "Skoftig", "percentage" => 0.076],
            ["name" => "Zeeburg Dubbelbock", "percentage" => 0.077],
            ["name" => "Christoffel Bok", "percentage" => 0.078],
            ["name" => "Mayflower", "percentage" => 0.078],
            ["name" => "Zeeburg Tripel", "percentage" => 0.078],
            ["name" => "Bavaria 8.6", "percentage" => 0.079],
            ["name" => "Bavaria 8.6 Red", "percentage" => 0.079],
            ["name" => "Bavaria 8.6 Black", "percentage" => 0.079],
            ["name" => "De Prael Scotch Ale", "percentage" => 0.079],
            ["name" => "Apeldoorns Tripel", "percentage" => 0.080],
            ["name" => "Burg Bier Tripel-B", "percentage" => 0.080],
            ["name" => "De Blauwe Krokodil", "percentage" => 0.080],
            ["name" => "Emelisse Black IPA", "percentage" => 0.080],
            ["name" => "Grof Geschut", "percentage" => 0.080],
            ["name" => "Grutte Pier Tripel", "percentage" => 0.080],
            ["name" => "Hillegonda Beginsel", "percentage" => 0.080],
            ["name" => "I.P.A.", "percentage" => 0.080],
            ["name" => "Java Triple", "percentage" => 0.080],
            ["name" => "La Trappe Tripel", "percentage" => 0.080],
            ["name" => "De Leckere Razende Swaen", "percentage" => 0.080],
            ["name" => "Maximus Stout 8", "percentage" => 0.080],
            ["name" => "Merakels", "percentage" => 0.080],
            ["name" => "Pek & Veren", "percentage" => 0.080],
            ["name" => "Dubbelbock", "percentage" => 0.080],
            ["name" => "Vagabond", "percentage" => 0.080],
            ["name" => "Praght Extra Stout", "percentage" => 0.080],
            ["name" => "Speculator", "percentage" => 0.080],
            ["name" => "Us Heit Dubbel Tarwe Bier", "percentage" => 0.080],
            ["name" => "Venloos Paeterke Triepel", "percentage" => 0.080],
            ["name" => "Wispe Tripel", "percentage" => 0.080],
            ["name" => "Zatte", "percentage" => 0.080],
            ["name" => "Zondebok", "percentage" => 0.080],
            ["name" => "Zundert", "percentage" => 0.080],
            ["name" => "Breugems Tripel", "percentage" => 0.081],
            ["name" => "Breugems Stoutert", "percentage" => 0.081],
            ["name" => "Bloed, Zweet & Tranen", "percentage" => 0.081],
            ["name" => "Sancti Adalberti Pastorale", "percentage" => 0.081],
            ["name" => "Gouverneur Triple", "percentage" => 0.082],
            ["name" => "Dubbel & Dwars", "percentage" => 0.082],
            ["name" => "Rook & Vuur", "percentage" => 0.082],
            ["name" => "Bavaria 8.6 Absinthe", "percentage" => 0.083],
            ["name" => "Sakamai", "percentage" => 0.084],
            ["name" => "Brand Zwaar Blond", "percentage" => 0.085],
            ["name" => "Bronckhorster Angus Tripel", "percentage" => 0.085],
            ["name" => "Budels Zware Dobber", "percentage" => 0.085],
            ["name" => "Czaar Peter", "percentage" => 0.085],
            ["name" => "Duits & Lauret Winterstout", "percentage" => 0.085],
            ["name" => "Emelisse Winterbier", "percentage" => 0.085],
            ["name" => "Euleteul Winter", "percentage" => 0.085],
            ["name" => "Gulpener WinterVrund", "percentage" => 0.085],
            ["name" => "Hertog Jan Tripel", "percentage" => 0.085],
            ["name" => "Jopen Koyt", "percentage" => 0.085],
            ["name" => "Schansbier Tripel", "percentage" => 0.085],
            ["name" => "Texels Tripel", "percentage" => 0.085],
            ["name" => "Vorst", "percentage" => 0.085],
            ["name" => "Christoffel Nobel", "percentage" => 0.087],
            ["name" => "Schansbier Imperial Stout", "percentage" => 0.088],
            ["name" => "Stoute Gijt", "percentage" => 0.088],
            ["name" => "Columbus", "percentage" => 0.090],
            ["name" => "Croy Tripel", "percentage" => 0.090],
            ["name" => "Dampegheest Winterwit", "percentage" => 0.090],
            ["name" => "Emelisse DIPA", "percentage" => 0.090],
            ["name" => "Hillegonda Top", "percentage" => 0.090],
            ["name" => "IJndejaars", "percentage" => 0.090],
            ["name" => "Jopen Trinitas Tripel", "percentage" => 0.090],
            ["name" => "Jopen Johannieter", "percentage" => 0.090],
            ["name" => "Limburgs Tripel", "percentage" => 0.090],
            ["name" => "Klap van de Molen", "percentage" => 0.090],
            ["name" => "De Prael D.I.P.A.", "percentage" => 0.090],
            ["name" => "Rames Shire Stout", "percentage" => 0.090],
            ["name" => "Struis", "percentage" => 0.090],
            ["name" => "Alfa Super Strong 9.2", "percentage" => 0.092],
            ["name" => "Maelstrøm", "percentage" => 0.092],
            ["name" => "Amarillo", "percentage" => 0.092],
            ["name" => ". Raptorr", "percentage" => 0.092],
            ["name" => "Hoeksch Winter", "percentage" => 0.093],
            ["name" => "Belhamel", "percentage" => 0.095],
            ["name" => "Burg Bier Gulle", "percentage" => 0.095],
            ["name" => "Texels Stormbock", "percentage" => 0.095],
            ["name" => "De Prael Barleywine", "percentage" => 0.096],
            ["name" => "Rooie Dop Double Oatmeal Stout", "percentage" => 0.096],
            ["name" => "Ambrozijn", "percentage" => 0.100],
            ["name" => "Emelisse Espresso Stout", "percentage" => 0.100],
            ["name" => "Gulpener Gladiator", "percentage" => 0.100],
            ["name" => "Hertog Jan Grand Prestige", "percentage" => 0.100],
            ["name" => "Jopen Ongelovige Thomas", "percentage" => 0.100],
            ["name" => "Jopen Meesterstuk", "percentage" => 0.100],
            ["name" => "La Trappe Quadrupel", "percentage" => 0.100],
            ["name" => "De Leckere Blauwe Bijl", "percentage" => 0.100],
            ["name" => "Hel & Verdoemenis", "percentage" => 0.100],
            ["name" => "Hemel & Aarde", "percentage" => 0.100],
            ["name" => "Oersoep Ontbijtbier", "percentage" => 0.100],
            ["name" => "Windkracht 10", "percentage" => 0.100],
            ["name" => "Zware Hufter", "percentage" => 0.100],
            ["name" => "Mooi & Meedogenloos", "percentage" => 0.102],
            ["name" => "Bavaria 8.6 Extreme", "percentage" => 0.105],
            ["name" => "Mastodont", "percentage" => 0.105],
            ["name" => "SGT. Nightvision", "percentage" => 0.105],
            ["name" => "Rasputin", "percentage" => 0.107],
            ["name" => "Emelisse Imperial Russian Stout", "percentage" => 0.110],
            ["name" => "Hart & Ziel", "percentage" => 0.110],
            ["name" => "Tsarina Esra", "percentage" => 0.110],
            ["name" => "Turf & Veen", "percentage" => 0.110],
            ["name" => "Armada", "percentage" => 0.110],
            ["name" => "Kopi Loewak", "percentage" => 0.112],
            ["name" => "De Prael Quadrupel", "percentage" => 0.115],
            ["name" => "Grolsch Krachtig Kanon", "percentage" => 0.116],
            ["name" => "Mout & Mocca", "percentage" => 0.116],
            ["name" => "Black Damnation", "percentage" => 0.130],
            ["name" => "Haver & Gort", "percentage" => 0.130],
            ["name" => "Bommen & Granaten", "percentage" => 0.150]
        ];

        foreach ($beers as $beer)
        {
            Beer::create($beer);
        }
    }
}
